# treefmt – universal formatter multiplexer
# See https://github.com/numtide/treefmt

excludes = [".git/**", "pnpm-lock.yaml", "node_modules/**", ".react-router/**", "build/**"]
walk = "filesystem"
verbose = 1

[formatter.oxfmt]
command = "pnpm"
options = ["exec", "oxfmt", "--write"]
includes = [
  "*.js",
  "*.jsx",
  "*.ts",
  "*.tsx",
  "*.json",
  "*.html",
  "*.css",
  "*.md",
  "*.yaml",
  "*.yml",
  "*.toml",
]
[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
